#!/bin/bash
sbatch run_bats_sortlisted_param_lise_1.slurm
sbatch run_bats_sortlisted_param_lise_2.slurm
sbatch run_bats_sortlisted_param_lise_3.slurm
sbatch run_bats_sortlisted_param_lise_4.slurm
sbatch run_bats_sortlisted_param_lise_5.slurm
sbatch run_bats_sortlisted_param_lise_6.slurm
sbatch run_bats_sortlisted_param_lise_7.slurm
sbatch run_bats_sortlisted_param_lise_8.slurm
sbatch run_bats_sortlisted_param_lise_9.slurm
sbatch run_bats_sortlisted_param_lise_10.slurm
