#!/bin/bash
sbatch run_bats_shortlisted28_param_emmy_1.slurm
sbatch run_bats_shortlisted28_param_emmy_2.slurm
sbatch run_bats_shortlisted28_param_emmy_3.slurm
sbatch run_bats_shortlisted28_param_emmy_4.slurm
sbatch run_bats_shortlisted28_param_emmy_5.slurm
sbatch run_bats_shortlisted28_param_emmy_6.slurm
sbatch run_bats_shortlisted28_param_emmy_7.slurm
sbatch run_bats_shortlisted28_param_emmy_8.slurm
sbatch run_bats_shortlisted28_param_emmy_9.slurm
sbatch run_bats_shortlisted28_param_emmy_10.slurm
